16. How to add a border (filled with 0's) around an existing array? (★☆☆)


In [ ]:
import numpy as np
Z = np.ones((4, 5))
print(Z)
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17.
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

```
# This is formatted as code
```



In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
# using np.diag()
x = np.diag(1+np.arange(4), k = -1)

# Printing the diagonal matrix 'x'
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
#create the array
Z = np.zeros ((8,8), dtype=int)
#Z[1::2, ::2] = 1 : Slice from 1st index row till 1+2+2… and fill all columns with 1 starting from 0th to 0+2+2… and so on.
#Z[::2, 1::2] = 1 : Slice from 0th row till 0+2+2… and fill all columns with 1 starting from 1 to 1+2+2+…..
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element

In [ ]:
#use the unravel command
index = np.unravel_index(100, (6,7,8))
print (index)

(1, 5, 4)


21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)


In [ ]:
W = np.tile( np.array([[0,1],[1,0]]), (4,4))
#creates an array 0,1 1,0 and is repeating 4 times
print(W)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. Normalize a 5x5 random matrix

In [ ]:
n = np.random.random((5, 5))
print("Original array")
print(n)
# Finding the max and min values in array 'n' using n.max() and n.min()
nmax, nmin = n.max(), n.min()
# to adjust the values in the array so that they fall within a certain range,
# typically between 0 and 1, or so that they
#have a standard normal distribution with a mean of 0 and a standard deviation of 1.

# Normalizing the array 'n' using min-max scaling: (n - nmin) / (nmax - nmin)
n = (n - nmin) / (nmax - nmin)

print("normalized")
print(n)

Original array
[[0.78365942 0.11667694 0.90399734 0.58519236 0.75968651]
 [0.95886339 0.80684879 0.35861113 0.64607807 0.11964286]
 [0.14974376 0.83679108 0.4446012  0.87587139 0.91870377]
 [0.24094091 0.17690279 0.45505226 0.71262198 0.78041012]
 [0.04259861 0.1470989  0.48781252 0.06110559 0.04007594]]
normalized
[[0.80930958 0.08337184 0.94028429 0.59329981 0.78321767]
 [1.         0.83454868 0.34669083 0.65956727 0.08659992]
 [0.11936147 0.8671376  0.44028166 0.90967225 0.95629064]
 [0.21861963 0.14892111 0.45165649 0.73199306 0.80577307]
 [0.00274565 0.11648283 0.48731247 0.02288849 0.        ]]


Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [ ]:
color = np.dtype([("r", np.ubyte),("g", np.ubyte),("b", np.ubyte),("a", np.ubyte)])


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)


In [ ]:
# random array of shape (5, 3)
b = np.random.random((5,3))
print("First array:")
print(b)

# random array of shape (3, 2)
c = np.random.random((3,2))
print("Second array:")
print(c)

# Computing the dot product of the two arrays
d = np.dot(b, c)

# Displaying result
print("Real matrix product is:")
print(d)

First array:
[[0.94225373 0.74781143 0.25006114]
 [0.93015699 0.34639816 0.20787299]
 [0.65975601 0.61982098 0.49290909]
 [0.43835229 0.05899221 0.4815432 ]
 [0.4978257  0.85541451 0.67884807]]
Second array:
[[0.70160965 0.90601584]
 [0.28142723 0.05973993]
 [0.75683561 0.68597049]]
Real matrix product is:
[[1.06080399 1.06990557]
 [0.90741869 1.00602551]
 [1.01037684 0.97289855]
 [0.68860326 0.73100274]
 [1.10379265 0.96781011]]


Given a 1D array, negate all elements which are between 3 and 8, in place.

In [ ]:
#create the array 0-12
x= np.arange(12)
#check values btw 3&8 and negate
x[(3 < x) & (x < 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11]


print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [31]:
2 << Z >> 2


array([   0,    1,    2,    4,    0,    0,    0,    0,  128,  256,  512,
       1024, 2048, 4096, 8192])

28. What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

In [32]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-32-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-32-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-32-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

29. How to round away from zero a float array ?

In [34]:
# Create a float array
array = np.array([-2.5, -1.8, 0.3, 1.5, 2.7])

# Round the elements away from zero using numpy.ceil
result = np.ceil(array)

# Print the resulting array
print(result)

[-2. -1.  1.  2.  3.]


How to find common values between two arrays?

In [36]:
arr1 = np.array([0, 1, 2, 3, 4, 5, 7, 9])
arr2 = [1, 3, 4, 7, 9]

# Common values between two arrays
print(np.intersect1d(arr1, arr2))


[1 3 4 7 9]
