31. How to ignore all numpy warnings (not recommended)

In [3]:
#using the seterr()
import numpy as np
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

FALSE

In [6]:
np.emath.sqrt(-1)

1j

In [7]:
np.sqrt(-1)

nan

How to get the dates of yesterday, today and tomorrow

In [8]:
# Import datetime and timedelta
# class from datetime module
from datetime import datetime, timedelta


# Get today's date
presentday = datetime.now() # or presentday = datetime.today()

# Get Yesterday
yesterday = presentday - timedelta(1)

# Get Tomorrow
tomorrow = presentday + timedelta(1)


# strftime() is to format date according to
# the need by converting them to string
print("Yesterday = ", yesterday.strftime('%d-%m-%Y'))
print("Today = ", presentday.strftime('%d-%m-%Y'))
print("Tomorrow = ", tomorrow.strftime('%d-%m-%Y'))


Yesterday =  15-02-2024
Today =  16-02-2024
Tomorrow =  17-02-2024


34. How to get all the dates corresponding to the month of July 2016

In [10]:
# Displaying the specified range of dates in July 2016 using NumPy's arange function
print("July, 2016")
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

July, 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [11]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


array([-1.5, -1.5, -1.5])

36. Extract the integer part of a random array of positive numbers using 4 different methods

In [13]:
Z = np.random.uniform(0,10,10)
print(Z)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[5.85236499 0.19198622 9.15281346 7.59084417 3.97348435 2.66482275
 4.97456246 4.92371383 7.82525219 6.49178909]
[5. 0. 9. 7. 3. 2. 4. 4. 7. 6.]
[5. 0. 9. 7. 3. 2. 4. 4. 7. 6.]
[5. 0. 9. 7. 3. 2. 4. 4. 7. 6.]
[5 0 9 7 3 2 4 4 7 6]
[5. 0. 9. 7. 3. 2. 4. 4. 7. 6.]


37. Create a 5x5 matrix with row values ranging from 0 to 4


In [14]:
R = np.zeros((5,5))
R += np.arange(5)
print(R)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38. Consider a generator function that generates 10 integers and use it to build an array

In [22]:
# Creating a generator 'iterable' using a generator expression that yields values from 0 to 9
i = (x for x in range(10))

# Creating a NumPy array using np.fromiter() by converting the elements obtained from the iterable
# Specifying the data type as np.int to create an array of integers
print(np.fromiter(i, np.float32))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


40. Create a random vector of size 10 and sort it (★★☆)


In [21]:
Z = np.random.random(10)
print (Z)
Z.sort()
print ("sorted")
print(Z)

[0.93372768 0.19207424 0.47490038 0.28486721 0.86751119 0.25641844
 0.39086035 0.30280033 0.41212101 0.83106937]
sorted
[0.19207424 0.25641844 0.28486721 0.30280033 0.39086035 0.41212101
 0.47490038 0.83106937 0.86751119 0.93372768]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [23]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


41. How to sum a small array faster than np.sum

In [25]:
C = np.arange(10)
print (C)
np.add.reduce(C)

[0 1 2 3 4 5 6 7 8 9]


45

42. Consider two random array A and B, check if they are equal

In [26]:
# Generating the first array 'arr1' with 8 random integers(0 or 1) using np.random.randint()
arr1 = np.random.randint(0, 2, 8)
print("First array:")
print(arr1)

# Generating the second array 'arr2' with 8 random integers (0 or 1) using np.random.randint()
arr2 = np.random.randint(0, 2, 8)
print("Second array:")
print(arr2)

# Checking if the two arrays 'arr1' and 'arr2' are equal using np.allclose()
# This function returns True if the two arrays are element-wise equal within a tolerance
array_equal = np.allclose(arr1, arr2)

# Printing whether the two arrays are equal or not
print("Test above two arrays are equal or not!")
print(array_equal)

First array:
[1 1 1 1 1 0 0 1]
Second array:
[1 1 0 1 1 0 0 0]
Test above two arrays are equal or not!
False


43. Make an array immutable (read-only)

In [27]:
Y = np.zeros(10)
Y.flags.writeable = False
Y[0] = 1

ValueError: assignment destination is read-only

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [29]:
arr1 = np.random.random(10)

print("Original array:")
print(arr1)

# Finding the index of the maximum value in the array using x.argmax()
# Replacing the maximum value with 0 using the index obtained from x.argmax()
arr1[arr1.argmax()] = 0

# Displaying the modified array where the maximum value has been replaced by 0
print("Maximum value replaced by 0:")
print(arr1)

Original array:
[0.57502688 0.58720421 0.15174461 0.63285522 0.63059398 0.23158882
 0.09734918 0.17707018 0.78742582 0.38570176]
Maximum value replaced by 0:
[0.57502688 0.58720421 0.15174461 0.63285522 0.63059398 0.23158882
 0.09734918 0.17707018 0.         0.38570176]
