1. Import the numpy package under the name np

In [2]:
import numpy as np

Print the numpy version and the configuration

In [3]:
print(np.__version__)


1.25.2


Create a null vector of size 10

In [4]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


to get the size of any array

In [6]:
array_1=np.arange(0,20,4,dtype=int)
#array size is
array_1.size
#array itemsize is
array_1.itemsize
memory_size = array_1.itemsize*array_1.size
print(memory_size)


40


How to get the documentation of the numpy add function from the command line

In [7]:
print(np.info(np. add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

Create a null vector of size 10 but the fifth value which is 1


In [8]:
# create null vector of size 10
null_vector1 = np.zeros(10)

# set the fifth value to 1
null_vector1[4] = 1

print(null_vector1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


 Create a vector with values ranging from 10 to 49

In [9]:
X = np.arange(10,50)
print (X)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


 Reverse a vector (first element becomes last

In [10]:
Y = np.arange(10,20)
Y = Y[::-1]
print (Y)

[19 18 17 16 15 14 13 12 11 10]


 Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
Nine = np.arange(9).reshape(3,3)
print (Nine)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


 Find indices of non-zero elements from [1,2,0,0,4,0]

In [12]:
not_zero = np.nonzero([1,2,0,0,4,0])
print(not_zero)

(array([0, 1, 4]),)


Create a 3x3 identity matrix

In [13]:
#all ones in the diagonal
Identity_mat= np.eye(3)
print (Identity_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a 3x3x3 array with random values

In [20]:
#make use of random
import random
Ra = np.random.uniform((3,3,3))
print (Ra)

[2.68285214 1.65182256 1.22105047]


Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
T = np.random.random((10,10))
print(T)
Tmin, Tmax = T.min(), T.max()
print(f"the max & Min Values', {Tmin},{Tmax}")

[[0.98117031 0.54275912 0.53811341 0.9683692  0.03883939 0.82187743
  0.52644209 0.74035006 0.72062573 0.64473146]
 [0.85555877 0.82834203 0.26877225 0.59571882 0.29585323 0.2453557
  0.09906406 0.24101645 0.70227473 0.48076583]
 [0.20478492 0.36101667 0.99967563 0.90738285 0.99021975 0.71945929
  0.77254831 0.01365829 0.92141094 0.49798995]
 [0.63705709 0.83181177 0.56322863 0.21844875 0.42415847 0.76689297
  0.29577634 0.59243191 0.35389005 0.33969491]
 [0.20973435 0.84153109 0.27874529 0.64252919 0.01674677 0.34144918
  0.21820572 0.87136131 0.42185696 0.10711217]
 [0.92532971 0.11201796 0.07826901 0.10307735 0.4897358  0.02076531
  0.14490289 0.7325811  0.53440645 0.57909443]
 [0.2843758  0.46007255 0.33415139 0.82656056 0.82609072 0.08635322
  0.81501005 0.62973933 0.21582136 0.28533976]
 [0.88321139 0.92197218 0.31658507 0.37263066 0.57670644 0.11932239
  0.04217186 0.00700979 0.48591565 0.20868248]
 [0.0231797  0.62644973 0.91067777 0.08672563 0.7596095  0.27087473
  0.59053151 

Create a random vector of size 30 and find the mean value

In [34]:
Thatee = np.random.random(30)
print(f"the vector has:{Thatee}")
mean_Thatee = Thatee.mean()
print (f"the mean is : {mean_Thatee} ")

the vector has:[0.09987687 0.27646354 0.29658579 0.54030585 0.2660563  0.66208836
 0.28344209 0.12525948 0.30764767 0.34298567 0.99514151 0.8107484
 0.42176681 0.40766459 0.42957006 0.42636718 0.54103627 0.47092959
 0.68694435 0.95470972 0.93671605 0.16719371 0.45542945 0.977965
 0.49791494 0.02528541 0.44907226 0.1826738  0.71538822 0.95465521]
the mean is : 0.49026280450395116 


Create a 2d array with 1 on the border and 0 inside

In [37]:
arr = np.ones((5,5))
print(arr)

# modify it
#This indexing operation sets the value of the inner elements of the array to zero by slicing the rows and columns
#from index 1 to the second last index (i.e., excluding the first and last rows and columns).
# The assignment operation (= 0) sets the selected elements to zero.
arr[1:-1,1:-1]=0

print(arr)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
