 Find the nearest value from a given value in an array

In [ ]:
import numpy as np

arr = np.array([12, 40, 65, 78, 10, 99, 30])
print("Array is : ", arr)

# element to which nearest value is to be found
x = 75
print("Value to which nearest element is to be found: ", x)

# calculate the difference array
difference_array = np.absolute(arr-x)

# find the index of minimum element from the array
index = difference_array.argmin()
print("Nearest element to the given values is : ", arr[index])
print("Index of nearest value is : ", index)

Array is :  [12 40 65 78 10 99 30]
Value to which nearest element is to be found:  75
Nearest element to the given values is :  78
Index of nearest value is :  3


Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator

In [ ]:
A = np.arange(3).reshape(3,1)
print(A)
B = np.arange(3).reshape(1,3)
print(B)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print("the result is")
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
the result is
[[0 1 2]
 [1 2 3]
 [2 3 4]]


Create an array class that has a name attribute (★★☆)

In [ ]:
class NameArr(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NameArr(np.arange(10), "range_10")
print (Z.name)

range_10


64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [ ]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)


In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
print(A)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print("sum is")
print(sum)

[[[[2 0 2 6]
   [9 4 6 1]
   [6 2 7 6]]

  [[6 7 3 4]
   [2 4 1 8]
   [2 9 4 8]]

  [[7 2 8 5]
   [4 0 0 9]
   [8 5 0 5]]

  [[9 5 2 7]
   [7 4 3 1]
   [4 6 1 1]]]


 [[[2 9 7 1]
   [7 4 9 7]
   [7 6 9 1]]

  [[0 0 9 0]
   [4 5 5 9]
   [7 7 2 7]]

  [[0 6 2 2]
   [1 4 0 8]
   [5 2 2 9]]

  [[1 6 8 9]
   [7 5 2 3]
   [1 8 6 9]]]


 [[[4 2 4 7]
   [7 5 4 6]
   [7 9 0 2]]

  [[8 0 0 5]
   [1 6 6 3]
   [5 4 9 5]]

  [[6 5 9 1]
   [2 5 8 8]
   [0 6 2 4]]

  [[6 2 9 7]
   [2 0 8 8]
   [2 0 6 8]]]]
sum is
[[51 58 53 50]
 [69 55 41 65]
 [57 52 56 58]]


68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)

In [ ]:
D = np.random.uniform(0,1,100)
print(D)
S = np.random.randint(0,10,100)
print(S)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print("mean of subset")
print(D_means)

[0.91148625 0.91225353 0.2619775  0.034428   0.76960565 0.41950761
 0.46257171 0.57706663 0.31487281 0.68664297 0.59102933 0.00369874
 0.98238405 0.32962227 0.81816849 0.69022418 0.94240152 0.00477614
 0.7563486  0.82298223 0.82599981 0.77072275 0.50200333 0.09320619
 0.66291409 0.40809659 0.26461717 0.40760729 0.99012991 0.2121652
 0.94201236 0.76032633 0.8274371  0.9768367  0.75128276 0.19931598
 0.42253725 0.74906587 0.05540963 0.98300676 0.25239841 0.51481938
 0.06963602 0.6747029  0.12505207 0.12723135 0.74354277 0.3046164
 0.41169573 0.65897164 0.40747594 0.02613282 0.56210493 0.21106558
 0.6571885  0.71340179 0.16415413 0.48803474 0.80009753 0.54164254
 0.23647723 0.34296034 0.12589633 0.49350202 0.1871564  0.66931632
 0.68341628 0.48336007 0.41600042 0.43251095 0.73897551 0.4959416
 0.79119095 0.89000928 0.8373891  0.34651384 0.48403365 0.29544882
 0.14284562 0.46819819 0.7347906  0.02982607 0.82351261 0.79033881
 0.88772316 0.6818001  0.19082563 0.55095946 0.27178013 0.1069487

69. How to get the diagonal of a dot product?

In [ ]:
A = np.random.uniform(0,1,(5,5))
print("array 1")
print(A)
B = np.random.uniform(0,1,(5,5))
print("array 2")
print(B)
np.einsum("ij,ji->i", A, B)



array 1
[[0.38506162 0.67899983 0.81487672 0.81770966 0.4845753 ]
 [0.67218195 0.2436223  0.48668155 0.64355605 0.90481915]
 [0.08289138 0.91418483 0.88484727 0.439366   0.56414411]
 [0.95126893 0.03980012 0.40456662 0.81549007 0.12981451]
 [0.6077839  0.12762575 0.76653417 0.79321306 0.19174725]]
array 2
[[0.60220288 0.33497828 0.35917093 0.19938912 0.92847809]
 [0.67227645 0.85996379 0.76997667 0.1610971  0.67948651]
 [0.08092809 0.38650297 0.2020044  0.54713161 0.45672724]
 [0.51066177 0.49055593 0.94704482 0.99502432 0.52307161]
 [0.37766194 0.76795222 0.25818096 0.67483618 0.78837941]]


array([1.35488594, 1.63333469, 1.47416677, 1.31647153, 1.56720787])

70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


72. How to swap two rows of an array?

In [ ]:
# Creating a NumPy array
num_arr = np.array([[1,3,1], [3,1,3], [2,9,2], [9,2,9]])
print("Original array:")
print(num_arr)

# Using np.roll() method for swapping array along row
num_arr = np.roll(num_arr,2,axis=0)

print("\nArray after swapping the rows:")
print(num_arr)

Original array:
[[1 3 1]
 [3 1 3]
 [2 9 2]
 [9 2 9]]

Array after swapping the rows:
[[2 9 2]
 [9 2 9]
 [1 3 1]
 [3 1 3]]


73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 19) ( 2, 59) ( 4, 14) ( 4, 22) ( 5, 28) ( 5, 76) (11, 11) (11, 31)
 (13, 56) (13, 79) (14, 22) (14, 24) (14, 64) (19, 59) (24, 64) (25, 46)
 (25, 49) (28, 76) (32, 48) (32, 90) (46, 49) (48, 90) (51, 84) (51, 90)
 (54, 90) (54, 92) (56, 79) (84, 90) (90, 92)]


74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


75. How to compute averages using a sliding window over an array?

In [ ]:
def moving_avrg(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
M = np.arange(20)
print(M)
print("moving average computation")
print(moving_avrg(M, n=3))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
moving average computation
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]



76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


77. How to negate a boolean, or to change the sign of a float inplace? (★★★)


In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-1.36285096e-01,  6.36654681e-01,  6.61742363e-01,  6.84510950e-01,
        4.79967427e-01, -6.97019337e-01,  6.72380939e-01, -1.38853600e-01,
        4.12682800e-01,  2.14149651e-01, -8.40385898e-02,  1.54630015e-01,
       -9.20745238e-01, -4.77285461e-01, -1.69571696e-01,  2.11150277e-01,
        5.66509907e-01,  1.99725535e-01, -1.42329842e-01,  4.86533643e-02,
       -1.65914218e-01,  2.80608115e-01, -7.44684425e-01, -2.31181549e-01,
       -5.80504467e-01, -1.80663194e-01, -7.42606702e-01,  6.46137552e-01,
       -5.77724372e-01,  2.41805219e-01, -7.26131215e-01, -2.87291823e-04,
        4.55154827e-01, -6.66739138e-01,  4.22060581e-01,  4.82059348e-01,
       -6.78345898e-01,  9.66482995e-01,  8.83777385e-01, -3.70961171e-01,
        7.24902344e-02,  7.24813252e-01,  7.41588042e-02,  4.72380369e-01,
        1.30051269e-01,  7.92307723e-01, -7.54591699e-01,  4.49720217e-01,
        4.43349751e-01,  3.65464141e-01,  4.46297574e-01,  3.58351196e-01,
       -3.49819470e-01,  

78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
import numpy as np
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[13.75252471 15.02405272  0.6515964   3.09641534  7.38038695  2.28167377
  3.72671002  6.57896727  5.28921261  6.10789293]


79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)


In [ ]:
# based on distance function from previous question
import numpy as np
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 1.42623117  5.43627675  4.44640151  0.15147256  8.98870748  8.48560475
   1.77684185  6.46563404  7.37532238 16.85977649]
 [13.81532198 10.01074866  6.38868734  2.09403804  5.27171682  4.29750255
  13.53818446  7.96706857  1.9900872   1.59809409]
 [ 1.25400956  2.21097537  3.64050655  2.15336214  5.421895    4.88594813
   1.55411117  4.288139    4.01954438 14.16217094]
 [13.48681078 12.55213505  0.05441103 12.83271564 10.94596446 11.6563178
  16.81021331  5.61990941 11.43954699  1.84895783]
 [ 0.84987754  0.32606518  8.88471217 10.70482887  1.02506692  0.86937393
   4.02350065  6.29616848  3.43649492 14.50450666]
 [ 1.62252206  2.72716791  1.45652548  1.13120475  6.92855687  6.93988717
   0.80945637  3.30896685  6.78042096 13.81733979]
 [ 2.33215805  2.82664332 12.71165644 12.95446032  2.49485153  0.12451529
   1.73389159  9.82244724  3.91345799 17.67106755]
 [ 4.45776069  0.1189112   1.13195566  1.70877963  4.82773036  5.26636284
   3.32600726  0.43632879  5.92875755 10.985561  ]
 

80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)

In [ ]:
import sliding
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

SyntaxError: invalid syntax (<ipython-input-5-cb62177066e3>, line 1)

81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

82. Compute a matrix rank (★★★)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


83. How to find the most frequent value in an array?`````````````````````````````````````````````

In [ ]:
# create array
z = np.array([1,2,4,8,5,1,2,7,7,7])
print("Original array:")
print(z)

print("Most frequent value in the above array:")
print(np.bincount(z).argmax())

Original array:
[1 2 4 8 5 1 2 7 7 7]
Most frequent value in the above array:
7


84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
import numpy as np
stride_tricks = np.lib.stride_tricks

arra1 = np.random.randint(0, 5, (10, 10))

# Displaying the original array 'arra1'
print("Original arrays:")
print(arra1)

# Specifying the block size 'n' as 3
n = 3

# Calculating dimensions 'i' and 'j' for the resulting array based on the original array shape
i = 1 + (arra1.shape[0] - 3)
j = 1 + (arra1.shape[1] - 3)

# Using stride tricks to create a view on 'arra1' with shape (i, j, n) representing contiguous 3by3blocks
result = stride_tricks.as_strided(arra1, shape=(i, j, n, n), strides=arra1.strides + arra1.strides)

# Displaying the contiguous 3by3 blocks obtained from the original array
print("\nContiguous 3by3 blocks:")
print(result)

Original arrays:
[[2 3 1 0 0 2 1 0 1 0]
 [4 1 2 1 0 4 3 0 3 4]
 [0 1 3 2 1 3 0 1 4 3]
 [0 2 2 4 3 3 4 3 4 4]
 [2 1 3 4 2 4 1 2 2 2]
 [2 4 1 3 1 1 1 0 1 3]
 [3 1 1 0 4 0 2 4 0 0]
 [0 3 3 2 1 1 4 2 1 4]
 [3 4 4 4 4 0 4 1 4 1]
 [3 4 3 2 2 2 2 3 0 2]]

Contiguous 3by3 blocks:
[[[[2 3 1]
   [4 1 2]
   [0 1 3]]

  [[3 1 0]
   [1 2 1]
   [1 3 2]]

  [[1 0 0]
   [2 1 0]
   [3 2 1]]

  [[0 0 2]
   [1 0 4]
   [2 1 3]]

  [[0 2 1]
   [0 4 3]
   [1 3 0]]

  [[2 1 0]
   [4 3 0]
   [3 0 1]]

  [[1 0 1]
   [3 0 3]
   [0 1 4]]

  [[0 1 0]
   [0 3 4]
   [1 4 3]]]


 [[[4 1 2]
   [0 1 3]
   [0 2 2]]

  [[1 2 1]
   [1 3 2]
   [2 2 4]]

  [[2 1 0]
   [3 2 1]
   [2 4 3]]

  [[1 0 4]
   [2 1 3]
   [4 3 3]]

  [[0 4 3]
   [1 3 0]
   [3 3 4]]

  [[4 3 0]
   [3 0 1]
   [3 4 3]]

  [[3 0 3]
   [0 1 4]
   [4 3 4]]

  [[0 3 4]
   [1 4 3]
   [3 4 4]]]


 [[[0 1 3]
   [0 2 2]
   [2 1 3]]

  [[1 3 2]
   [2 2 4]
   [1 3 4]]

  [[3 2 1]
   [2 4 3]
   [3 4 2]]

  [[2 1 3]
   [4 3 3]
   [4 2 4]]

  [[1 3 0]
   [3 3 4]
 

85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 9 12 13 17 11]
 [12  9 11 11 12]
 [13 11  8 42 10]
 [17 11 42  7 15]
 [11 12 10 15  7]]


86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)


In [ ]:
x = np.ones((16,16))
print (x)
k = 4
S = np.add.reduceat(np.add.reduceat(x, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


88. How to implement the Game of Life using numpy arrays? (★★★)


89. How to get the n largest values of an array (★★★)


In [1]:
import numpy as np

# Creating an array 'x' containing numbers from 0 to 9 using arange() function
x = np.arange(10)

# Displaying the original array 'x'
print("Original array:")
print(x)

# Shuffling the elements in array 'x'
np.random.shuffle(x)

# Selecting the 'n' largest elements in 'x' using argsort and slicing
n = 1
print(x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [2]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


91. How to create a record array from a regular array? (★★★)


In [4]:
# Creating a NumPy array 'arra1' containing records with names and corresponding scores
arra1 = np.array([("Colin Powell", 88.5, 90),
                 ("Uhuru Kenyatta", 87, 99),
                 ("Whitney Houston", 85.5, 91)])

# Displaying the original array 'arra1'
print("Original arrays:")
print(arra1)

# Converting the array 'arra1' into a record array with named fields 'col1', 'col2', and 'col3'
result = np.core.records.fromarrays(arra1.T,
                                    names='col1, col2, col3',
                                    formats='S80, f8, i8')

# Displaying the record array 'result'
print("\nRecord array;")
print(result)

Original arrays:
[['Colin Powell' '88.5' '90']
 ['Uhuru Kenyatta' '87' '99']
 ['Whitney Houston' '85.5' '91']]

Record array;
[(b'Colin Powell', 88.5, 90) (b'Uhuru Kenyatta', 87. , 99)
 (b'Whitney Houston', 85.5, 91)]


92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [5]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.51 s ± 209 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
221 ms ± 16.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
228 ms ± 41.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)



93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [2]:
import numpy as np
A = np.random.randint(0,5,(8,3))
print(A)
B = np.random.randint(0,5,(2,2))
print(B)

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)


[[0 4 2]
 [1 0 0]
 [4 3 4]
 [2 4 4]
 [2 4 1]
 [0 0 2]
 [2 3 2]
 [2 3 2]]
[[3 0]
 [0 4]]
[0 1 2 5]


94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [5]:
nums = np.random.randint(0, 4, (10, 3))

# Displaying the original array 'nums'
print("Original vector:")
print(nums)

# Checking for rows where consecutive elements are not equal within each row
# using np.logical_and.reduce and axis=1 to check row-wise
new_nums = np.logical_and.reduce(nums[:, 1:] == nums[:, :-1], axis=1)

# Filtering out rows with unequal consecutive values and storing in 'result'
result = nums[~new_nums]

# Displaying rows with unequal consecutive values
print("\nRows with unequal values:")
print(result)

Original vector:
[[2 1 1]
 [3 2 1]
 [3 0 0]
 [1 2 0]
 [3 3 1]
 [2 0 0]
 [0 3 1]
 [2 1 2]
 [2 3 3]
 [2 0 3]]

Rows with unequal values:
[[2 1 1]
 [3 2 1]
 [3 0 0]
 [1 2 0]
 [3 3 1]
 [2 0 0]
 [0 3 1]
 [2 1 2]
 [2 3 3]
 [2 0 3]]


95. Convert a vector of ints into a matrix binary representation (★★★)

In [7]:

# the array
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])

B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


Given a two dimensional array, how to extract unique rows

In [9]:
# Create a 2D numpy array
arr1 = np.array([[11, 11, 12, 11],
                     [13, 11, 12, 11],
                     [16, 11, 12, 11],
                     [11, 11, 12, 11]])

uniqueRows = np.unique(arr1, axis=0)


# print the output result
print('Unique Rows:',
      uniqueRows, sep = '\n')

Unique Rows:
[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]]


7. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★

In [11]:
A = np.random.uniform(0,1,10)
print(A)
B = np.random.uniform(0,1,10)
print(B)
print("sum")
np.einsum('i->', A)       # np.sum(A)
print("mul")
np.einsum('i,i->i', A, B) # A * B
print("inner")
np.einsum('i,i', A, B)    # np.inner(A, B)
print("outer")
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

[0.15309136 0.20132529 0.68697262 0.38658426 0.30996558 0.94915637
 0.6066771  0.568745   0.61954245 0.84551499]
[0.08309006 0.18497903 0.28203452 0.8709397  0.47747704 0.38673165
 0.98065313 0.67821376 0.88580762 0.8379003 ]
sum
mul
inner
outer


array([[0.01272037, 0.02831869, 0.04317705, 0.13333334, 0.07309761,
        0.05920527, 0.15012952, 0.10382866, 0.13560949, 0.12827529],
       [0.01672813, 0.03724096, 0.05678068, 0.17534218, 0.0961282 ,
        0.07785886, 0.19743027, 0.13654158, 0.17833547, 0.16869052],
       [0.0570806 , 0.12707553, 0.19374999, 0.59831173, 0.32801366,
        0.26567406, 0.67368185, 0.46591428, 0.60852558, 0.57561456],
       [0.03212131, 0.07150998, 0.10903011, 0.33669158, 0.18458511,
        0.14950437, 0.37910506, 0.26218676, 0.34243928, 0.32391906],
       [0.02575506, 0.05733713, 0.08742099, 0.26996132, 0.14800145,
        0.1198735 , 0.30396871, 0.21022292, 0.27456987, 0.25972025],
       [0.07886546, 0.17557402, 0.26769486, 0.82665796, 0.45320038,
        0.36706881, 0.93079317, 0.64373091, 0.84076995, 0.79529841],
       [0.05040884, 0.11222254, 0.17110388, 0.52837917, 0.28967439,
        0.23462124, 0.5949398 , 0.41145675, 0.5373992 , 0.50833492],
       [0.04725706, 0.1052059 , 0.1604057

98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?


99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).